# Generated by Django 3.2.19 on 2026-05-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarina', '0004_ordermodel_orderpaymentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True),
        ),
    ]
