# Generated by Django 3.2.19 on 2026-05-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarina', '0006_otpmodel_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
