# Generated by Django 3.2.19 on 2026-06-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarina', '0009_auto_20260625_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategorymodel',
            options={'ordering': ['-priority', 'name'], 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher values appear first'),
        ),
    ]
